/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0Lrjgph56QI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"

export function adminSpecificProd() {
  return (
    (<div className="flex flex-col gap-6 p-6 md:p-8 lg:p-10">
      <div className="flex items-center gap-4">
        <h1 className="text-2xl font-bold">Editar producto</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button variant="outline" size="sm">
            Descartar
          </Button>
          <Button size="sm">Guardar producto</Button>
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle>Detalles del producto</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Nombre</Label>
                <Input id="name" type="text" defaultValue="Camiseta de algodón" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="description">Descripción</Label>
                <Textarea
                  id="description"
                  rows={4}
                  defaultValue="Camiseta de algodón suave y cómoda." />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="price">Precio</Label>
                <Input id="price" type="number" defaultValue={19.99} />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Categoría</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <Label htmlFor="category">Categoría</Label>
              <Select id="category" defaultValue="ropa">
                <SelectTrigger>
                  <SelectValue placeholder="Selecciona una categoría" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ropa">Ropa</SelectItem>
                  <SelectItem value="accesorios">Accesorios</SelectItem>
                  <SelectItem value="hogar">Hogar</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Estado</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-2">
                <Checkbox id="out-of-stock" />
                <Label htmlFor="out-of-stock">Agotado</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox id="favorite" />
                <Label htmlFor="favorite">Favorito</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox id="visible" defaultChecked />
                <Label htmlFor="visible">Visible</Label>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}
