/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ATN0Vcc67VG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Badge } from "@/components/ui/badge"

export function ProductsR() {
  return (
    (<div className="bg-gray-100 p-4">
      <div className="bg-white rounded-lg shadow-md p-4 mb-4">
        <div className="flex items-center justify-between">
          <h1 className="text-xl font-bold">Déjàvu | El Yerro Menu</h1>
          <div className="flex items-center space-x-2">
            <ShareIcon className="w-6 h-6 text-gray-600" />
            <BookmarkIcon className="w-6 h-6 text-gray-600" />
            <ExpandIcon className="w-6 h-6 text-gray-600" />
          </div>
        </div>
        <p className="text-gray-500">elyerromenu.com</p>
      </div>
      <div className="bg-white rounded-lg shadow-md p-4 mb-4">
        <div className="flex items-center space-x-2 mb-2">
          <Badge variant="destructive">CERRADO</Badge>
          <p className="text-gray-500">Abre en 1h y 45m</p>
        </div>
        <h2 className="text-2xl font-bold mb-2">DÉJÀVU</h2>
        <img
          src="/placeholder.svg"
          alt="Restaurant"
          className="w-full h-auto rounded-lg mb-4" />
        <div className="flex items-center space-x-2 mb-2">
          <StarIcon className="w-4 h-4 text-yellow-500" />
          <p className="text-gray-700">4.2 (13 reseñas) · CUP ($$ - $$$$)</p>
        </div>
        <p className="text-gray-700 mb-2">
          Trabajamos todos los días excepto los martes de 10am a 10pm Domicilios de 11am a 9pm
        </p>
        <a href="#" className="text-blue-500">
          Ver más...
        </a>
        <div className="flex items-center space-x-2 mt-2">
          <Badge variant="secondary">Santa Clara, Villa Clara</Badge>
          <Badge variant="success">Domicilio</Badge>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md p-4 mb-4">
        <h3 className="text-xl font-bold mb-4">ENTRANTES</h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-gray-100 rounded-lg p-2">
            <img
              src="/placeholder.svg"
              alt="Chicharritas"
              className="w-full h-auto rounded-lg mb-2" />
            <h4 className="text-lg font-bold">Chicharritas</h4>
            <p className="text-gray-700">250,00 CUP</p>
          </div>
          <div className="bg-gray-100 rounded-lg p-2">
            <img
              src="/placeholder.svg"
              alt="Papas fritas"
              className="w-full h-auto rounded-lg mb-2" />
            <h4 className="text-lg font-bold">Papas fritas</h4>
            <p className="text-gray-700">150 g de papas fritas</p>
            <p className="text-gray-700">500,00 CUP</p>
          </div>
          <div className="bg-gray-100 rounded-lg p-2">
            <img
              src="/placeholder.svg"
              alt="Croquetas"
              className="w-full h-auto rounded-lg mb-2" />
            <h4 className="text-lg font-bold">Croquetas</h4>
            <p className="text-gray-700">600,00 CUP</p>
          </div>
          <div className="bg-gray-100 rounded-lg p-2">
            <img
              src="/placeholder.svg"
              alt="Nuggets de pollo"
              className="w-full h-auto rounded-lg mb-2" />
            <h4 className="text-lg font-bold">Nuggets de pollo</h4>
            <p className="text-gray-700">600,00 CUP</p>
          </div>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md p-4 mb-4">
        <h3 className="text-xl font-bold mb-4">DE CERDO</h3>
        <div className="bg-gray-100 rounded-lg p-2">
          <img
            src="/placeholder.svg"
            alt="De Cerdo"
            className="w-full h-auto rounded-lg mb-2" />
          <Badge variant="destructive">AGOTADO</Badge>
        </div>
      </div>
    </div>)
  );
}

function BookmarkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>)
  );
}


function ExpandIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m21 21-6-6m6 6v-4.8m0 4.8h-4.8" />
      <path d="M3 16.2V21m0 0h4.8M3 21l6-6" />
      <path d="M21 7.8V3m0 0h-4.8M21 3l-6 6" />
      <path d="M3 7.8V3m0 0h4.8M3 3l6 6" />
    </svg>)
  );
}


function ShareIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
